### ISSUE TITLE
auto compile codec2 on github release action

### ISSUE THREAD

**Issue by DJ2LS** [DJ2LS/FreeDATA#149]
we should automatically build and link libcodec2.
We need to static link some dependencies for crosscompiling https://github.com/drowe67/codec2/pull/307

**Comment by kronenpj** [comment]
I'd like to be sure what this is asking for. From what I see in the GitHub actions files, `codec2` is being built from source on Linux and Mac but not Windows. Please tell me if I'm reading these lines incorrectly:
```yml
      - name: Build codec2 Linux
        if: matrix.os == 'ubuntu-20.04'
        working-directory: tnc
        run: |
          git clone https://github.com/drowe67/codec2.git
          cd codec2 && mkdir build_linux && cd build_linux
          cmake ../
          make
```
```yml
      - name: Build codec2 macOS
        if: matrix.os == 'macos-10.15'
        working-directory: tnc
        run: |
          git clone https://github.com/drowe67/codec2.git
          cd codec2 && mkdir build_mac && cd build_mac
          cmake ../
          make
```
If my interpretation is correct, this issue asks for the Windows `codec2` to be compiled.
